version: "3.8"
services:
  api:
    build:
      # prod
      context: ./
      dockerfile: ./api/Dockerfile.prod
    env_file:
      - ./.env
    volumes:
      - ./api:/api/app
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"

  client:
    build:
      # prod
      context: ./
      dockerfile: ./client/Dockerfile.prod
    env_file:
      - ./.env
    volumes:
      - ./client/src:/app/src
      - ./client/static:/app/static
    depends_on:
      - api
    links:
      - api
    ports:
      - "${CLIENT_PORT}:3000"
    restart: unless-stopped

volumes:
  api:
    driver: local